//> using publish.organization "io.get-coursier"
//> using publish.name "class-path-util"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.repository "central"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/coursier/class-path-util"
//> using publish.versionControl "github:coursier/class-path-util"
//> using publish.developer "Alex Archambault||https://github.com/alexarchambault"
